export const formData = {
  title: "Example Form",
  allToolProps: [
    {
      key: 0,
      tool: "date time",
      toolId: 0,
      bold: false,
      italic: false,
      underline: false,
      textSize: 14,
      x: 59,
      y: 37,
    },
    {
      key: 1,
      tool: "text",
      toolId: 1,
      bold: false,
      italic: false,
      underline: false,
      textSize: 14,
      x: 60,
      y: 92,
    },
    {
      key: 2,
      tool: "time",
      toolId: 2,
      bold: false,
      italic: false,
      underline: false,
      textSize: 14,
      x: 60,
      y: 146,
    },
    {
      key: 3,
      tool: "digit input",
      toolId: 3,
      bold: false,
      italic: false,
      underline: false,
      textSize: 14,
      x: 60,
      y: 203,
    },
    {
      key: 4,
      tool: "date only",
      toolId: 4,
      bold: false,
      italic: false,
      underline: false,
      textSize: 14,
      x: 316,
      y: 37,
    },
    {
      key: 5,
      tool: "checkbox",
      toolId: 5,
      bold: false,
      italic: false,
      underline: false,
      textSize: 14,
      x: 318,
      y: 102,
    },
    {
      key: 6,
      tool: "static-label",
      toolId: 6,
      bold: false,
      italic: false,
      underline: false,
      textSize: 14,
      x: 323,
      y: 141,
      label: "Example",
    },
    {
      key: 7,
      tool: "text-area",
      toolId: 7,
      bold: false,
      italic: false,
      underline: false,
      textSize: 14,
      x: 320,
      y: 186,
    },
    {
      key: 8,
      tool: "radio",
      toolId: 8,
      bold: false,
      italic: false,
      underline: false,
      textSize: 14,
      x: 352,
      y: 102,
    },
  ],
};
