export const ROOT = process.env.PUBLIC_URL + '/'
export const CREATOR = process.env.PUBLIC_URL + '/creator'
export const PREVIEW = process.env.PUBLIC_URL + '/creator/preview'
export const RESPONDER = process.env.PUBLIC_URL+ '/responder'
export const VIEWER = process.env.PUBLIC_URL + '/viewer'
export const DESTROYER = process.env.PUBLIC_URL + '/destroyer'